# Generated by Django 5.0.14 on 2026-07-10 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Libellé')),
                ('deductible_solde', models.BooleanField(default=True, verbose_name='Déductible du solde')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('jours_decomptes', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Jours décomptés')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_N1', 'En attente N1'), ('EN_ATTENTE_RH', 'En attente RH'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('motif', models.TextField(blank=True, null=True, verbose_name='Motif')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/', verbose_name='Pièce jointe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaves.leavetype', verbose_name='Type de congé')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField(choices=[(1, 'Niveau 1 (Manager)'), (2, 'Niveau 2 (RH)')], verbose_name='Niveau')),
                ('decision', models.CharField(choices=[('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé')], max_length=15, verbose_name='Décision')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('decided_at', models.DateTimeField(auto_now_add=True, verbose_name='Décidé le')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='given_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Approbateur')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leaves.leaverequest', verbose_name='Demande de congé')),
            ],
        ),
    ]
