# Generated by Django 5.0.14 on 2026-07-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='requires_attachment',
            field=models.BooleanField(default=False, verbose_name='Pièce jointe obligatoire'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_N1', 'En attente N1'), ('EN_ATTENTE_RH', 'En attente RH'), ('VALIDE', 'Approuvée'), ('REFUSE', 'Rejetée'), ('EN_ATTENTE_ANNULATION', "En attente d'annulation"), ('ANNULE', 'Annulée'), ('CLOTURE', 'Clôturée')], default='BROUILLON', max_length=30, verbose_name='Statut'),
        ),
    ]
