# Generated by Django 5.0.14 on 2026-07-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leavetype_requires_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='notice_days',
            field=models.IntegerField(default=0, verbose_name='Délai de préavis (jours)'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_motif',
            field=models.BooleanField(default=False, verbose_name='Motif obligatoire'),
        ),
    ]
