# Generated by Django 5.0.14 on 2026-07-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE_STATUS', 'Mise à jour du statut'), ('DELETE', 'Suppression'), ('ADJUST_BALANCE', 'Ajustement du solde')], max_length=50, verbose_name='Action')),
                ('ancien_statut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nouveau statut')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='ID Utilisateur')),
            ],
        ),
    ]
