# Generated by Django 5.0.14 on 2026-07-10 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='leave_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='leaves.leaverequest', verbose_name='Demande de congé'),
        ),
    ]
