# Generated by Django 5.0.14 on 2026-07-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Détails/Motif'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_employee_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Employé Cible'),
        ),
    ]
