# Generated by Django 5.0.14 on 2026-07-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog_details_auditlog_target_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlap_threshold_percent', models.IntegerField(default=50, help_text="Pourcentage maximum d'employés d'un même département pouvant être en congé simultanément.", verbose_name="Seuil d'alerte chevauchement (%)")),
            ],
            options={
                'verbose_name': "Paramètres de l'entreprise",
                'verbose_name_plural': "Paramètres de l'entreprise",
            },
        ),
    ]
