# Generated by Django 5.0.14 on 2026-07-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE_STATUS', 'Mise à jour du statut'), ('DELETE', 'Suppression'), ('ADJUST_BALANCE', 'Ajustement du solde'), ('ACCESS_DOCUMENT', 'Accès au document')], max_length=50, verbose_name='Action'),
        ),
    ]
