# Generated by Django 5.0.14 on 2026-07-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_intern',
            field=models.BooleanField(default=False, verbose_name='Est stagiaire'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('EMPLOYE', 'Employé'), ('MANAGER_N1', 'Manager N1'), ('RH', 'RH'), ('ADMIN', 'Administrateur'), ('DG', 'Directeur Général')], default='EMPLOYE', max_length=20, verbose_name='Rôle'),
        ),
    ]
