# Generated by Django 5.0.14 on 2026-07-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SOUMISSION', 'Soumission'), ('DECISION', 'Décision'), ('RAPPEL', 'Rappel'), ('CAMPAGNE', 'Campagne')], max_length=20, verbose_name='Type'),
        ),
    ]
